### ISSUE TITLE
Why reverse the order in the future subdecoder ?

### ISSUE THREAD

**Issue by thangld201** [ictnlp/SeerForcingNMT#3]
Hi, I've read and really appreciated your team's work on the paper. However, I find one detail not clear to me, which is why we have to reverse the order in the future subdecoder's output. Since, the two only differ in the attention mask matrix, meaning the first token of the past subdecoder should only attend to itself, and the same applies to the last token of the future subdecoder. What's the point in reversing the order, such that these two tokens can now point to the same index ? I mean, they only attend to themselves, there are no particular past-future information combination here, just the first and last token altogether.

**Comment by thangld201** [comment]
Would you mind explaining this part @gushu333 ?

**Comment by gushu333** [comment]
Hi, @thangld201 thanks for your attention. 

It is true that the past subdecoder and future subdecoder differ only in the attention mask matrix in theory. But in our implementation,   we just reverse the decoder input for the past subdecoder, so we don't need to modify the mask matrix.
https://github.com/ictnlp/SeerForcingNMT/blob/b84a435579c3a2217c5ef2409b346347e788ae5d/fairseq/models/transformer.py#L778-L781

Then, we reverse the future subdecoder output again in the top layer of the decoder, making sure the hidden states of the same token can be combined together. 
https://github.com/ictnlp/SeerForcingNMT/blob/b84a435579c3a2217c5ef2409b346347e788ae5d/fairseq/modules/transformer_layer.py#L605-L612

**Comment by thangld201** [comment]
I got it now. Since the input to one subdecoder was reversed initially, which meant it must be reversed later on before fusing. It's confusing since the fact that the input is reversed before being fed to the subdecoder wasn't mentioned in the paper. I got it now, thanks for your clarification.
